### ISSUE TITLE
Switching to v8 causing crash [nativescript-algolia]

### ISSUE THREAD

**Issue by keerl** [NativeScript/ns-v8ios-runtime#82]
Here is another instance where my app is crashing when I switch to v8.

I am using [nativescript-algolia](https://github.com/arpit2438735/nativescript-algolia) and if I do a simple search on the old ios runtime it works perfectly, but when I use the new runtime and try to run a search query the app crashes instantly with no errors again.

Here is a demo app that shows the problem: [v8-algolia-bug.zip](https://github.com/NativeScript/ns-v8ios-runtime/files/5537445/v8-algolia-bug.zip)

I have to go into the crash logs to find this error:

![Screen Shot 2020-11-13 at 7 40 42 AM](https://user-images.githubusercontent.com/24727492/99084186-dfc36480-2583-11eb-94f4-08ffcdf08a7c.png)

I once again believe this is not a problem with the Algolia plugin, but in fact a problem with the v8 runtime.

Doesn't really seem like the iOS v8 runtime is ready for prime time with multiple issues like this.

Also, why are there absolutely no errors in the console when something goes wrong with the v8 runtime? It makes things difficult to debug.

**Comment by NathanaelA** [comment]
Can you try the newly release 7.0.6 and see if it fixes your issue?

**Comment by keerl** [comment]
Issue still exists on 7.0.6.

**Comment by darind** [comment]
@keerl, thanks for the detailed bug report. While this issue has been observed in the v8 iOS runtime, it is not directly related to it. The reason for the crash is incorrect use of the API in the [plugin code](https://github.com/arpit2438735/nativescript-algolia/blob/master/src/index.ios.ts#L22):

```typescript
let client;

export class Algolia {
    constructor(appID: string, apiKey: string) {
        client = Client.alloc();
        client.initWithAppIDApiKey(appID, apiKey);
    };

    ...
}
```

Inside this constructor we allocate the client instance and then call the `initWithAppIDApiKey` method on it without taking into account the result of this method.

A correct implementation would be:

```typescript
constructor(appID: string, apiKey: string) {
    client = Client.alloc().initWithAppIDApiKey(appID, apiKey);
}
```

or if you prefer:

```typescript
constructor(appID: string, apiKey: string) {
    client = Client.alloc();
    client = client.initWithAppIDApiKey(appID, apiKey);
}
```

The reason why the original code worked in the old runtime was because there was some *incorrect* mechanism in it where uninitialized objects were automagically initialized.

So I would suggest you opening an issue in the algolia plugin repo.

**Comment by keerl** [comment]
@darind wow, thanks for looking into this and giving this detailed info, very helpful! I will look into updating the plugin.

**Comment by nampil** [comment]
I was having the same problem and I was able to solve it using @darind suggestion:
```
constructor(appID: string, apiKey: string) {
    client = Client.alloc();
    client = client.initWithAppIDApiKey(appID, apiKey);
}
```
Thnks!
